"""
Revision ID: 0fca1b0b627c
Revises: 85f35f55ce97
Create Date: 2025-10-21 16:29:48.392729

"""
from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '0fca1b0b627c'
down_revision = '85f35f55ce97'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('courses', 'price')
    # ### end Alembic commands ###
