"""
Revision ID: 85f35f55ce97
Revises: 71639c0368a7
Create Date: 2025-10-21 10:33:18.651243

"""
from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '85f35f55ce97'
down_revision = '71639c0368a7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
