"""
Revision ID: aa0e941fe12b
Revises: 0fca1b0b627c
Create Date: 2025-10-21 16:42:26.992202

"""
from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = 'aa0e941fe12b'
down_revision = '0fca1b0b627c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teachers', sa.Column('join_date', sa.Date(), nullable=True))
    op.add_column('teachers', sa.Column('birthdate', sa.Date(), nullable=True))
    op.add_column('teachers', sa.Column('styles', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teachers', 'styles')
    op.drop_column('teachers', 'birthdate')
    op.drop_column('teachers', 'join_date')
    # ### end Alembic commands ###
